### ISSUE TITLE
Make the map work with search and filters

### ISSUE THREAD

**Issue by andreasdri** [eit-for-en-bedre-verden/idrettsanlegginorge#26]

**Comment by andreasdri** [comment]
`/api/v1/Idrettsanlegg/?format=json&kartData__Latitude__gt=57&kartData__Longitude__gt=0&limit=500&offset=0` takes too long time. Maybe provide an endpoint where you only get coordinates and idrettsanlegg id, @tordsk ?

**Comment by tordsk** [comment]
Kart data goodness #27 is a proposed solution to the issue and provides significant boost to response times
